In [1]:
# Import required libraries

import pandas as pd
import numpy as np

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully!")

Libraries Imported Successfully!

In [3]:
# Load 2009-2010 dataset

df1 = pd.read_excel(
    "../data/raw/online_retail_II.xlsx",
    sheet_name="Year 2009-2010"
)

# Load 2010-2011 dataset

df2 = pd.read_excel(
    "../data/raw/online_retail_II.xlsx",
    sheet_name="Year 2010-2011"
)

# Load second retail dataset

df3 = pd.read_excel(
    "../data/raw/Online Retail.xlsx"
)

print("Files Loaded Successfully!")

Files Loaded Successfully!

In [4]:
print("Dataset 1 Shape :", df1.shape)
print("Dataset 2 Shape :", df2.shape)
print("Dataset 3 Shape :", df3.shape)

Dataset 1 Shape : (525461, 8)
Dataset 2 Shape : (541910, 8)
Dataset 3 Shape : (541909, 8)

In [5]:
print(df1.columns)

print(df2.columns)

print(df3.columns)

Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')
Index(['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'Price', 'Customer ID', 'Country'],
      dtype='str')
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [6]:
# Rename columns in df1

df1.rename(columns={
    "Invoice":"InvoiceNo",
    "Price":"UnitPrice",
    "Customer ID":"CustomerID"
}, inplace=True)

# Rename columns in df2

df2.rename(columns={
    "Invoice":"InvoiceNo",
    "Price":"UnitPrice",
    "Customer ID":"CustomerID"
}, inplace=True)

In [7]:
print(df1.columns)

print(df2.columns)

print(df3.columns)

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')
Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='str')

In [9]:
df = pd.concat([df1, df2, df3], ignore_index=True)

print("Combined Dataset Shape :", df.shape)

Combined Dataset Shape : (1609280, 8)

In [10]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1609280 entries, 0 to 1609279
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1609280 non-null  object
 1   StockCode    1609280 non-null  object
 2   Description  1603444 non-null  object
 3   Quantity     1609280 non-null  int64
 4   InvoiceDate  1609280 non-null  datetime64[us]
 5   UnitPrice    1609280 non-null  float64
 6   CustomerID   1231193 non-null  float64
 7   Country      1609280 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 118.8+ MB

In [12]:
df.describe()

           Quantity                 InvoiceDate     UnitPrice    CustomerID
count  1.609280e+06                     1609280  1.609280e+06  1.231193e+06
mean   9.808698e+00  2011-03-05 09:37:06.173742  4.636499e+00  1.531243e+04
min   -8.099500e+04         2009-12-01 07:45:00 -5.359436e+04  1.234600e+04
25%    1.000000e+00         2010-10-19 14:30:00  1.250000e+00  1.396900e+04
50%    3.000000e+00         2011-03-30 13:05:00  2.100000e+00  1.522000e+04
75%    1.000000e+01         2011-09-14 12:14:00  4.130000e+00  1.679500e+04
max    8.099500e+04         2011-12-09 12:50:00  3.897000e+04  1.828700e+04
std    1.892047e+02                         NaN  1.152285e+02  1.702901e+03

In [13]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      5836
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     378087
Country             0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(576244)

In [15]:
df.to_csv(
    "../data/processed/combined_raw.csv",
    index=False
)

print("Combined dataset saved successfully!")

Combined dataset saved successfully!

In [16]:
df.shape

(1609280, 8)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1609280 entries, 0 to 1609279
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1609280 non-null  object
 1   StockCode    1609280 non-null  object
 2   Description  1603444 non-null  object
 3   Quantity     1609280 non-null  int64
 4   InvoiceDate  1609280 non-null  datetime64[us]
 5   UnitPrice    1609280 non-null  float64
 6   CustomerID   1231193 non-null  float64
 7   Country      1609280 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 118.8+ MB

In [18]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      5836
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     378087
Country             0
dtype: int64

In [19]:
df.duplicated().sum()

np.int64(576244)

In [20]:
df = pd.concat([df1, df2], ignore_index=True)

In [21]:
df.shape
df.duplicated().sum()

np.int64(34335)

In [22]:
df_clean = df.copy()

In [23]:
print("Before:", df_clean.shape)

df_clean.drop_duplicates(inplace=True)

print("After :", df_clean.shape)

Before: (1067371, 8)
After : (1033036, 8)

In [24]:
df_clean.isnull().sum()

InvoiceNo           0
StockCode           0
Description      4275
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     235151
Country             0
dtype: int64

In [25]:
df_clean.dropna(subset=["Description"], inplace=True)

In [26]:
df_clean["CustomerID"] = (
    df_clean["CustomerID"]
    .fillna(0)
    .astype(int)
)

In [27]:
df_clean = df_clean[df_clean["Quantity"] > 0]

In [28]:
df_clean = df_clean[df_clean["UnitPrice"] > 0]

In [29]:
df_clean["Revenue"] = (
    df_clean["Quantity"] *
    df_clean["UnitPrice"]
)

In [30]:
df_clean["Year"] = df_clean["InvoiceDate"].dt.year
df_clean["Month"] = df_clean["InvoiceDate"].dt.month
df_clean["Day"] = df_clean["InvoiceDate"].dt.day
df_clean["Week"] = df_clean["InvoiceDate"].dt.isocalendar().week
df_clean["DayName"] = df_clean["InvoiceDate"].dt.day_name()

In [31]:
print(df_clean.shape)

df_clean.head()

(1007914, 14)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Week,DayName
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,1,49,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,1,49,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,1,49,Tuesday

In [32]:
df_clean.to_csv(
    "../data/processed/cleaned_retail_data.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [33]:
df.shape
df.duplicated().sum()
df_clean.shape

(1007914, 14)

In [34]:
df.shape

(1067371, 8)

In [35]:
df.duplicated().sum()

np.int64(34335)

In [36]:
df_clean.shape

(1007914, 14)