In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [2]:
df = pd.read_csv(
    "../data/processed/cleaned_retail_data.csv",
    parse_dates=["InvoiceDate"]
)

df.head()

C:\Users\vicky\AppData\Local\Temp\ipykernel_13248\3831162418.py:1: DtypeWarning: Columns (0: InvoiceNo) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Week,DayName
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,1,49,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,1,49,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,1,49,Tuesday

In [3]:
df["Date"] = df["InvoiceDate"].dt.date

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue,Year,Month,Day,Week,DayName,Date
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085,United Kingdom,83.4,2009,12,1,49,Tuesday,2009-12-01
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday,2009-12-01
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085,United Kingdom,81.0,2009,12,1,49,Tuesday,2009-12-01
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085,United Kingdom,100.8,2009,12,1,49,Tuesday,2009-12-01
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085,United Kingdom,30.0,2009,12,1,49,Tuesday,2009-12-01

In [4]:
daily_sales = (
    df.groupby(
        ["Date", "StockCode"]
    )
    .agg(
        Units_Sold=("Quantity", "sum"),
        Revenue=("Revenue", "sum")
    )
    .reset_index()
)

daily_sales.head()

         Date StockCode  Units_Sold  Revenue
0  2009-12-01     10002          12     10.2
1  2009-12-01     10120          60     12.6
2  2009-12-01    10123C           3      3.9
3  2009-12-01    10123G           2      3.4
4  2009-12-01     10125           5      5.1

In [5]:
daily_sales["Date"] = pd.to_datetime(daily_sales["Date"])

In [6]:
daily_sales = daily_sales.sort_values(
    ["StockCode", "Date"]
)

In [7]:
daily_sales["Year"] = daily_sales["Date"].dt.year

daily_sales["Month"] = daily_sales["Date"].dt.month

daily_sales["Week"] = daily_sales["Date"].dt.isocalendar().week

daily_sales["Day"] = daily_sales["Date"].dt.day

daily_sales["DayOfWeek"] = daily_sales["Date"].dt.dayofweek

In [8]:
daily_sales["Lag_1"] = (
    daily_sales.groupby("StockCode")["Units_Sold"]
    .shift(1)
)

daily_sales["Lag_7"] = (
    daily_sales.groupby("StockCode")["Units_Sold"]
    .shift(7)
)

In [9]:
daily_sales["Rolling_7"] = (
    daily_sales.groupby("StockCode")["Units_Sold"]
    .transform(
        lambda x: x.rolling(7).mean()
    )
)

In [10]:
daily_sales.dropna(inplace=True)

In [11]:
daily_sales.to_csv(
    "../data/processed/daily_sales_features.csv",
    index=False
)

print("Feature dataset saved successfully!")

Feature dataset saved successfully!